server:
  port: 9097

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    hikari:
      pool-name: logicea-card-api-pool
      maximum-pool-size: 200
      allow-pool-suspension: true
mvc:
  throw-exception-if-no-handler-found: true