server:
  port: 9097

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true

  datasource:
    hikari:
      pool-name: logicea-card-api-pool
      maximum-pool-size: 200
      allow-pool-suspension: true
    url: jdbc:mysql://localhost:3306/logiceaCard
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: logicea
    password: logicea123
mvc:
  throw-exception-if-no-handler-found: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html